### ISSUE TITLE
Where did you get your BlocksData.xml?

### ISSUE THREAD

**Issue by qnnnnez** [padillah/ScWorldEditor#7]
Well, when I unpack Content.pak in Survivalcraft.apk, I only got BlocksData.txt, while most of text files are formatted in XML.
Here is my tool to pack/unpack Content.pak: [scpak](https://github.com/qnnnnez/scpak)
I am really grateful for your work on this.

**Comment by padillah** [comment]
I got that directly from the developer - Kaalus. I needed to be able to load texture data but there was nothing to indicate the texture offset so I asked him and he gave me this xml.

**Comment by qnnnnez** [comment]
@padillah 
Now we have 32 bit for every block, so the Chunks.dat file format has been changed.

[Edit]
And file format given [here](https://kaalus.wordpress.com/chunks-dat-file-format/) has also been updated.

**Comment by qnnnnez** [comment]
And that‘s what I got: [BlocksData.txt](https://raw.githubusercontent.com/qnnnnez/SC-Chinese/d0a47aee2888ae645bff3c2a532a7f1dd4ca1f29/Content/BlocksData.txt)
